### ISSUE TITLE
META: matplotlib issues

### ISSUE THREAD

**Issue by mdboom** [pyodide/matplotlib-pyodide#9]
- [x] Interactivity -- need to write a new HTML Canvas-based backend
- [x] tri module -- skipped for now due to some compilation issues
- [x] qhull module -- skipped for now due to some compilation issues
- [ ] custom fonts -- for now, it only has access to the "shipped" fonts
- [x] HiDPI (retina) support -- it currently displays a low-rez image
- [x] Reduce size -- clean out unnecessary stuff, like GUI backends, external tex support

**Comment by rth** [comment]
Since most of the items are resolved, I'm going to close this. Opened https://github.com/pyodide/matplotlib-pyodide/issues/14 about the last remaining point.
